{{- range .Values.global.clusters }}
        {{- $cluster := set . "useClusterNamespaces" $.Values.global.useClusterNamespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
        {{- include "clusterNamespacedName" $cluster | indent 2 }}
  labels: {{ include "labels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ if $.Values.global.useClusterNamespaces }}Cluster{{ end }}Role
  name: {{ include "fullname" $ }}
subjects:
  - kind: ServiceAccount
            {{- include "clusterNamespacedName" $cluster | indent 4 }}
        {{- end }}
