apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fullname" . }}
  labels: {{ include "labels" . | nindent 4 }}
data:
  config: |
    apiVersion: config.admiralty.io/v1alpha1
    kind: Scheduler
    useClusterNamespaces: {{ .Values.global.useClusterNamespaces }}
          {{- with .Values.global.clusters }}
    clusters: {{ toYaml . | nindent 6 }}
          {{- end }}
