---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: poddecisions.multicluster.admiralty.io
spec:
  group: multicluster.admiralty.io
  names:
    categories:
      - decisions
      - decision
      - dec
    kind: PodDecision
    plural: poddecisions
    shortNames:
      - poddec
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            template:
              type: object
          required:
            - template
          type: object
        status:
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
