---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: statefulsetobservations.multicluster.admiralty.io
spec:
  group: multicluster.admiralty.io
  names:
    categories:
      - observations
      - observation
      - obs
    kind: StatefulSetObservation
    plural: statefulsetobservations
    shortNames:
      - statefulsetobs
      - ssobs
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
        status:
          properties:
            liveState:
              type: object
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
