---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: nodepools.multicluster.admiralty.io
spec:
  group: multicluster.admiralty.io
  names:
    kind: NodePool
    plural: nodepools
    shortNames:
      - np
  scope: Cluster
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            allocatable:
              type: object
            maxNodeCount:
              format: int32
              type: integer
            minNodeCount:
              format: int32
              type: integer
            price:
              type: object
            selector:
              type: object
          required:
            - minNodeCount
            - maxNodeCount
          type: object
        status:
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
